//! GENERATED FILE -- do not edit by hand.
//!
//! GNU bash 5.3 builtin help texts, extracted verbatim from
//! third_party/bash/builtins/*.def by the rules of
//! builtins/mkbuiltins.c (parse loop 575-636, add_documentation
//! 767-785, write_documentation 1391-1516: `$`-directives, doc lines
//! keep leading whitespace and lose trailing whitespace, blank lines
//! before the first doc line are dropped, `#`-prefixed lines are
//! conditional-compilation guards that never reach the runtime doc).
//!
//! Rendering contract (builtins/help.def):
//!   long help  : `name: short_doc` then every doc line prefixed by
//!               BASE_INDENT (4) spaces (help.def:172 show_longdoc)
//!   help -d    : `name - <first doc line>` (help.def:245 show_desc)
//!   help -s    : `name: short_doc` only (sflag suppresses longdoc)
//!   help -m    : pseudo-manpage (help.def:287 show_manpage)
//!
//! Regenerate with target/gc/helptext-gen/gen_help_texts.py (needs
//! canonical-names.txt produced by
//! `MSYS_NO_PATHCONV=1 wsl /usr/local/bin/bash -c 'help -d "*"'`).

/// One entry of GNU bash's shell_builtins[] help table, in table order.
pub(crate) struct HelpTopic {
    /// shell_builtins[i].name -- the exact match key (`help '(( ... ))'`).
    pub(crate) name: &'static str,
    /// shell_builtins[i].short_doc -- the $SHORT_DOC synopsis line.
    pub(crate) short_doc: &'static str,
    /// Long-documentation lines ($BUILTIN..$END body, `#`-guard lines
    /// dropped) with mkbuiltins' whitespace rules already applied;
    /// rendered with a 4-space indent (BASE_INDENT, builtins.h:50).
    pub(crate) doc: &'static [&'static str],
    /// mkbuiltins leaves the doc string ending in `\n` when the last
    /// text line is followed by a `#`-guard line (the separator at
    /// mkbuiltins.c:1479 keys on raw line order, not emitted lines);
    /// the rendered page then carries one final EMPTY line.
    pub(crate) trailing_newline: bool,
}

/// GNU bash 5.3 shell_builtins[] help table in display order.
#[rustfmt::skip]
pub(crate) static HELP_TOPICS_TABLE: &[HelpTopic] = &[
    // reserved.def
    HelpTopic {
        name: "!",
        short_doc: "! PIPELINE",
        doc: &[
            "Execute PIPELINE, which can be a simple command, and negate PIPELINE's",
            "return status.",
            "",
            "Exit Status:",
            "The logical negation of PIPELINE's return status.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "%",
        short_doc: "job_spec [&]",
        doc: &[
            "Resume job in foreground.",
            "",
            "Equivalent to the JOB_SPEC argument to the `fg' command.  Resume a",
            "stopped or background job.  JOB_SPEC can specify either a job name",
            "or a job number.  Following JOB_SPEC with a `&' places the job in",
            "the background, as if the job specification had been supplied as an",
            "argument to `bg'.",
            "",
            "Exit Status:",
            "Returns the status of the resumed job.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "(( ... ))",
        short_doc: "(( expression ))",
        doc: &[
            "Evaluate arithmetic expression.",
            "",
            "The EXPRESSION is evaluated according to the rules for arithmetic",
            "evaluation.  Equivalent to `let \"EXPRESSION\"'.",
            "",
            "Exit Status:",
            "Returns 1 if EXPRESSION evaluates to 0; returns 0 otherwise.",
        ],
        trailing_newline: false,
    },
    // source.def
    HelpTopic {
        name: ".",
        short_doc: ". [-p path] filename [arguments]",
        doc: &[
            "Execute commands from a file in the current shell.",
            "",
            "Read and execute commands from FILENAME in the current shell. If the",
            "-p option is supplied, the PATH argument is treated as a colon-",
            "separated list of directories to search for FILENAME. If -p is not",
            "supplied, $PATH is searched to find FILENAME. If any ARGUMENTS are",
            "supplied, they become the positional parameters when FILENAME is executed.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed in FILENAME; fails if",
            "FILENAME cannot be read.",
        ],
        trailing_newline: false,
    },
    // colon.def
    HelpTopic {
        name: ":",
        short_doc: ":",
        doc: &[
            "Null command.",
            "",
            "No effect; the command does nothing.",
            "",
            "Exit Status:",
            "Always succeeds.",
        ],
        trailing_newline: false,
    },
    // test.def
    HelpTopic {
        name: "[",
        short_doc: "[ arg... ]",
        doc: &[
            "Evaluate conditional expression.",
            "",
            "This is a synonym for the \"test\" builtin, but the last argument must",
            "be a literal `]', to match the opening `['.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "[[ ... ]]",
        short_doc: "[[ expression ]]",
        doc: &[
            "Execute conditional command.",
            "",
            "Returns a status of 0 or 1 depending on the evaluation of the conditional",
            "expression EXPRESSION.  Expressions are composed of the same primaries used",
            "by the `test' builtin, and may be combined using the following operators:",
            "",
            "  ( EXPRESSION )\tReturns the value of EXPRESSION",
            "  ! EXPRESSION\t\tTrue if EXPRESSION is false; else false",
            "  EXPR1 && EXPR2\tTrue if both EXPR1 and EXPR2 are true; else false",
            "  EXPR1 || EXPR2\tTrue if either EXPR1 or EXPR2 is true; else false",
            "",
            "When the `==' and `!=' operators are used, the string to the right of",
            "the operator is used as a pattern and pattern matching is performed.",
            "When the `=~' operator is used, the string to the right of the operator",
            "is matched as a regular expression.",
            "",
            "The && and || operators do not evaluate EXPR2 if EXPR1 is sufficient to",
            "determine the expression's value.",
            "",
            "Exit Status:",
            "0 or 1 depending on value of EXPRESSION.",
        ],
        trailing_newline: false,
    },
    // alias.def
    HelpTopic {
        name: "alias",
        short_doc: "alias [-p] [name[=value] ... ]",
        doc: &[
            "Define or display aliases.",
            "",
            "Without arguments, `alias' prints the list of aliases in the reusable",
            "form `alias NAME=VALUE' on standard output.",
            "",
            "Otherwise, an alias is defined for each NAME whose VALUE is given.",
            "A trailing space in VALUE causes the next word to be checked for",
            "alias substitution when the alias is expanded.",
            "",
            "Options:",
            "  -p\tprint all defined aliases in a reusable format",
            "",
            "Exit Status:",
            "alias returns true unless a NAME is supplied for which no alias has been",
            "defined.",
        ],
        trailing_newline: false,
    },
    // fg_bg.def
    HelpTopic {
        name: "bg",
        short_doc: "bg [job_spec ...]",
        doc: &[
            "Move jobs to the background.",
            "",
            "Place the jobs identified by each JOB_SPEC in the background, as if they",
            "had been started with `&'.  If JOB_SPEC is not present, the shell's notion",
            "of the current job is used.",
            "",
            "Exit Status:",
            "Returns success unless job control is not enabled or an error occurs.",
        ],
        trailing_newline: false,
    },
    // bind.def
    HelpTopic {
        name: "bind",
        short_doc: "bind [-lpsvPSVX] [-m keymap] [-f filename] [-q name] [-u name] [-r keyseq] [-x keyseq:shell-command] [keyseq:readline-function or readline-command]",
        doc: &[
            "Set Readline key bindings and variables.",
            "",
            "Bind a key sequence to a Readline function or a macro, or set a",
            "Readline variable.  The non-option argument syntax is equivalent to",
            "that found in ~/.inputrc, but must be passed as a single argument:",
            "e.g., bind '\"\\C-x\\C-r\": re-read-init-file'.",
            "",
            "Options:",
            "  -m  keymap         Use KEYMAP as the keymap for the duration of this",
            "                     command.  Acceptable keymap names are emacs,",
            "                     emacs-standard, emacs-meta, emacs-ctlx, vi, vi-move,",
            "                     vi-command, and vi-insert.",
            "  -l                 List names of functions.",
            "  -P                 List function names and bindings.",
            "  -p                 List functions and bindings in a form that can be",
            "                     reused as input.",
            "  -S                 List key sequences that invoke macros and their values",
            "  -s                 List key sequences that invoke macros and their values",
            "                     in a form that can be reused as input.",
            "  -V                 List variable names and values",
            "  -v                 List variable names and values in a form that can",
            "                     be reused as input.",
            "  -q  function-name  Query about which keys invoke the named function.",
            "  -u  function-name  Unbind all keys which are bound to the named function.",
            "  -r  keyseq         Remove the binding for KEYSEQ.",
            "  -f  filename       Read key bindings from FILENAME.",
            "  -x  keyseq:shell-command\tCause SHELL-COMMAND to be executed when",
            "\t\t\t\tKEYSEQ is entered.",
            "  -X                 List key sequences bound with -x and associated commands",
            "                     in a form that can be reused as input.",
            "",
            "If arguments remain after option processing, the -p and -P options treat",
            "them as readline command names and restrict output to those names.",
            "",
            "Exit Status:",
            "bind returns 0 unless an unrecognized option is given or an error occurs.",
        ],
        trailing_newline: false,
    },
    // break.def
    HelpTopic {
        name: "break",
        short_doc: "break [n]",
        doc: &[
            "Exit for, while, or until loops.",
            "",
            "Exit a FOR, WHILE or UNTIL loop.  If N is specified, break N enclosing",
            "loops.",
            "",
            "Exit Status:",
            "The exit status is 0 unless N is not greater than or equal to 1.",
        ],
        trailing_newline: false,
    },
    // builtin.def
    HelpTopic {
        name: "builtin",
        short_doc: "builtin [shell-builtin [arg ...]]",
        doc: &[
            "Execute shell builtins.",
            "",
            "Execute SHELL-BUILTIN with arguments ARGs without performing command",
            "lookup.  This is useful when you wish to reimplement a shell builtin",
            "as a shell function, but need to execute the builtin within the function.",
            "",
            "Exit Status:",
            "Returns the exit status of SHELL-BUILTIN, or false if SHELL-BUILTIN is",
            "not a shell builtin.",
        ],
        trailing_newline: false,
    },
    // caller.def
    HelpTopic {
        name: "caller",
        short_doc: "caller [expr]",
        doc: &[
            "Return the context of the current subroutine call.",
            "",
            "Without EXPR, returns \"$line $filename\".  With EXPR, returns",
            "\"$line $subroutine $filename\"; this extra information can be used to",
            "provide a stack trace.",
            "",
            "The value of EXPR indicates how many call frames to go back before the",
            "current one; the top frame is frame 0.",
            "",
            "Exit Status:",
            "Returns 0 unless the shell is not executing a shell function or EXPR",
            "is invalid.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "case",
        short_doc: "case WORD in [PATTERN [| PATTERN]...) COMMANDS ;;]... esac",
        doc: &[
            "Execute commands based on pattern matching.",
            "",
            "Selectively execute COMMANDS based upon WORD matching PATTERN.  The",
            "`|' is used to separate multiple patterns.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // cd.def
    HelpTopic {
        name: "cd",
        short_doc: "cd [-L|[-P [-e]]] [-@] [dir]",
        doc: &[
            "Change the shell working directory.",
            "",
            "Change the current directory to DIR.  The default DIR is the value of the",
            "HOME shell variable. If DIR is \"-\", it is converted to $OLDPWD.",
            "",
            "The variable CDPATH defines the search path for the directory containing",
            "DIR.  Alternative directory names in CDPATH are separated by a colon (:).",
            "A null directory name is the same as the current directory.  If DIR begins",
            "with a slash (/), then CDPATH is not used.",
            "",
            "If the directory is not found, and the shell option `cdable_vars' is set,",
            "the word is assumed to be  a variable name.  If that variable has a value,",
            "its value is used for DIR.",
            "",
            "Options:",
            "  -L\tforce symbolic links to be followed: resolve symbolic",
            "\t\tlinks in DIR after processing instances of `..'",
            "  -P\tuse the physical directory structure without following",
            "\t\tsymbolic links: resolve symbolic links in DIR before",
            "\t\tprocessing instances of `..'",
            "  -e\tif the -P option is supplied, and the current working",
            "\t\tdirectory cannot be determined successfully, exit with",
            "\t\ta non-zero status",
            "  -@\ton systems that support it, present a file with extended",
            "\t\tattributes as a directory containing the file attributes",
            "",
            "The default is to follow symbolic links, as if `-L' were specified.",
            "`..' is processed by removing the immediately previous pathname component",
            "back to a slash or the beginning of DIR.",
            "",
            "Exit Status:",
            "Returns 0 if the directory is changed, and if $PWD is set successfully when",
            "-P is used; non-zero otherwise.",
        ],
        trailing_newline: false,
    },
    // command.def
    HelpTopic {
        name: "command",
        short_doc: "command [-pVv] command [arg ...]",
        doc: &[
            "Execute a simple command or display information about commands.",
            "",
            "Runs COMMAND with ARGS suppressing  shell function lookup, or display",
            "information about the specified COMMANDs.  Can be used to invoke commands",
            "on disk when a function with the same name exists.",
            "",
            "Options:",
            "  -p    use a default value for PATH that is guaranteed to find all of",
            "        the standard utilities",
            "  -v    print a single word indicating the command or filename that",
            "        invokes COMMAND",
            "  -V    print a more verbose description of each COMMAND",
            "",
            "Exit Status:",
            "Returns exit status of COMMAND, or failure if COMMAND is not found.",
        ],
        trailing_newline: false,
    },
    // complete.def
    HelpTopic {
        name: "compgen",
        short_doc: "compgen [-V varname] [-abcdefgjksuv] [-o option] [-A action] [-G globpat] [-W wordlist] [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [word]",
        doc: &[
            "Display possible completions depending on the options.",
            "",
            "Intended to be used from within a shell function generating possible",
            "completions.  If the optional WORD argument is present, generate matches",
            "against WORD.",
            "",
            "If the -V option is supplied, store the possible completions in the indexed",
            "array VARNAME instead of printing them to the standard output.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or an error occurs.",
        ],
        trailing_newline: false,
    },
    // complete.def
    HelpTopic {
        name: "complete",
        short_doc: "complete [-abcdefgjksuv] [-pr] [-DEI] [-o option] [-A action] [-G globpat] [-W wordlist] [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]",
        doc: &[
            "Specify how arguments are to be completed by Readline.",
            "",
            "For each NAME, specify how arguments are to be completed.  If no options",
            "or NAMEs are supplied, display existing completion specifications in a way",
            "that allows them to be reused as input.",
            "",
            "Options:",
            "  -p\tprint existing completion specifications in a reusable format",
            "  -r\tremove a completion specification for each NAME, or, if no",
            "\t\tNAMEs are supplied, all completion specifications",
            "  -D\tapply the completions and actions as the default for commands",
            "\t\twithout any specific completion defined",
            "  -E\tapply the completions and actions to \"empty\" commands --",
            "\t\tcompletion attempted on a blank line",
            "  -I\tapply the completions and actions to the initial (usually the",
            "\t\tcommand) word",
            "",
            "When completion is attempted, the actions are applied in the order the",
            "uppercase-letter options are listed above. If multiple options are supplied,",
            "the -D option takes precedence over -E, and both take precedence over -I.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or an error occurs.",
        ],
        trailing_newline: false,
    },
    // complete.def
    HelpTopic {
        name: "compopt",
        short_doc: "compopt [-o|+o option] [-DEI] [name ...]",
        doc: &[
            "Modify or display completion options.",
            "",
            "Modify the completion options for each NAME, or, if no NAMEs are supplied,",
            "the completion currently being executed.  If no OPTIONs are given, print",
            "the completion options for each NAME or the current completion specification.",
            "",
            "Options:",
            "\t-o option\tSet completion option OPTION for each NAME",
            "\t-D\t\tChange options for the \"default\" command completion",
            "\t-E\t\tChange options for the \"empty\" command completion",
            "\t-I\t\tChange options for completion on the initial word",
            "",
            "Using `+o' instead of `-o' turns off the specified option.",
            "",
            "Arguments:",
            "",
            "Each NAME refers to a command for which a completion specification must",
            "have previously been defined using the `complete' builtin.  If no NAMEs",
            "are supplied, compopt must be called by a function currently generating",
            "completions, and the options for that currently-executing completion",
            "generator are modified.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or NAME does not",
            "have a completion specification defined.",
        ],
        trailing_newline: false,
    },
    // break.def
    HelpTopic {
        name: "continue",
        short_doc: "continue [n]",
        doc: &[
            "Resume for, while, or until loops.",
            "",
            "Resumes the next iteration of the enclosing FOR, WHILE or UNTIL loop.",
            "If N is specified, resumes the Nth enclosing loop.",
            "",
            "Exit Status:",
            "The exit status is 0 unless N is not greater than or equal to 1.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "coproc",
        short_doc: "coproc [NAME] command [redirections]",
        doc: &[
            "Create a coprocess named NAME.",
            "",
            "Execute COMMAND asynchronously, with the standard output and standard",
            "input of the command connected via a pipe to file descriptors assigned",
            "to indices 0 and 1 of an array variable NAME in the executing shell.",
            "The default NAME is \"COPROC\".",
            "",
            "Exit Status:",
            "The coproc command returns an exit status of 0.",
        ],
        trailing_newline: false,
    },
    // declare.def
    HelpTopic {
        name: "declare",
        short_doc: "declare [-aAfFgiIlnrtux] [name[=value] ...] or declare -p [-aAfFilnrtux] [name ...]",
        doc: &[
            "Set variable values and attributes.",
            "",
            "Declare variables and give them attributes.  If no NAMEs are given,",
            "display the attributes and values of all variables.",
            "",
            "Options:",
            "  -f\trestrict action or display to function names and definitions",
            "  -F\trestrict display to function names only (plus line number and",
            "\t\tsource file when debugging)",
            "  -g\tcreate global variables when used in a shell function; otherwise",
            "\t\tignored",
            "  -I\tif creating a local variable, inherit the attributes and value",
            "\t\tof a variable with the same name at a previous scope",
            "  -p\tdisplay the attributes and value of each NAME",
            "",
            "Options which set attributes:",
            "  -a\tto make NAMEs indexed arrays (if supported)",
            "  -A\tto make NAMEs associative arrays (if supported)",
            "  -i\tto make NAMEs have the `integer' attribute",
            "  -l\tto convert the value of each NAME to lower case on assignment",
            "  -n\tmake NAME a reference to the variable named by its value",
            "  -r\tto make NAMEs readonly",
            "  -t\tto make NAMEs have the `trace' attribute",
            "  -u\tto convert the value of each NAME to upper case on assignment",
            "  -x\tto make NAMEs export",
            "",
            "Using `+' instead of `-' turns off the given attribute, except for a,",
            "A, and r.",
            "",
            "Variables with the integer attribute have arithmetic evaluation (see",
            "the `let' command) performed when the variable is assigned a value.",
            "",
            "When used in a function, `declare' makes NAMEs local, as with the `local'",
            "command.  The `-g' option suppresses this behavior.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or a variable",
            "assignment error occurs.",
        ],
        trailing_newline: false,
    },
    // pushd.def
    HelpTopic {
        name: "dirs",
        short_doc: "dirs [-clpv] [+N] [-N]",
        doc: &[
            "Display directory stack.",
            "",
            "Display the list of currently remembered directories.  Directories",
            "find their way onto the list with the `pushd' command; you can get",
            "back up through the list with the `popd' command.",
            "",
            "Options:",
            "  -c\tclear the directory stack by deleting all of the elements",
            "  -l\tdo not print tilde-prefixed versions of directories relative",
            "\t\tto your home directory",
            "  -p\tprint the directory stack with one entry per line",
            "  -v\tprint the directory stack with one entry per line prefixed",
            "\t\twith its position in the stack",
            "",
            "Arguments:",
            "  +N\tDisplays the Nth entry counting from the left of the list",
            "\t\tshown by dirs when invoked without options, starting with",
            "\t\tzero.",
            "",
            "  -N\tDisplays the Nth entry counting from the right of the list",
            "\t\tshown by dirs when invoked without options, starting with",
            "\t\tzero.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or an error occurs.",
        ],
        trailing_newline: false,
    },
    // jobs.def
    HelpTopic {
        name: "disown",
        short_doc: "disown [-h] [-ar] [jobspec ... | pid ...]",
        doc: &[
            "Remove jobs from current shell.",
            "",
            "Removes each JOBSPEC argument from the table of active jobs.  Without",
            "any JOBSPECs, the shell uses its notion of the current job.",
            "",
            "Options:",
            "  -a\tremove all jobs if JOBSPEC is not supplied",
            "  -h\tmark each JOBSPEC so that SIGHUP is not sent to the job if the",
            "\t\tshell receives a SIGHUP",
            "  -r\tremove only running jobs",
            "",
            "Exit Status:",
            "Returns success unless an invalid option or JOBSPEC is given.",
        ],
        trailing_newline: false,
    },
    // echo.def
    HelpTopic {
        name: "echo",
        short_doc: "echo [-neE] [arg ...]",
        doc: &[
            "Write arguments to the standard output.",
            "",
            "Display the ARGs, separated by a single space character and followed by a",
            "newline, on the standard output.",
            "",
            "Options:",
            "  -n\tdo not append a newline",
            "  -e\tenable interpretation of the following backslash escapes",
            "  -E\texplicitly suppress interpretation of backslash escapes",
            "",
            "`echo' interprets the following backslash-escaped characters:",
            "  \\a\talert (bell)",
            "  \\b\tbackspace",
            "  \\c\tsuppress further output",
            "  \\e\tescape character",
            "  \\E\tescape character",
            "  \\f\tform feed",
            "  \\n\tnew line",
            "  \\r\tcarriage return",
            "  \\t\thorizontal tab",
            "  \\v\tvertical tab",
            "  \\\\\tbackslash",
            "  \\0nnn\tthe character whose ASCII code is NNN (octal).  NNN can be",
            "\t\t0 to 3 octal digits",
            "  \\xHH\tthe eight-bit character whose value is HH (hexadecimal).  HH",
            "\t\tcan be one or two hex digits",
            "  \\uHHHH\tthe Unicode character whose value is the hexadecimal value HHHH.",
            "\t\tHHHH can be one to four hex digits.",
            "  \\UHHHHHHHH the Unicode character whose value is the hexadecimal value",
            "\t\tHHHHHHHH. HHHHHHHH can be one to eight hex digits.",
            "",
            "Exit Status:",
            "Returns success unless a write error occurs.",
        ],
        trailing_newline: false,
    },
    // enable.def
    HelpTopic {
        name: "enable",
        short_doc: "enable [-a] [-dnps] [-f filename] [name ...]",
        doc: &[
            "Enable and disable shell builtins.",
            "",
            "Enables and disables builtin shell commands.  Disabling allows you to",
            "execute a disk command which has the same name as a shell builtin",
            "without using a full pathname.",
            "",
            "Options:",
            "  -a\tprint a list of builtins showing whether or not each is enabled",
            "  -n\tdisable each NAME or display a list of disabled builtins",
            "  -p\tprint the list of builtins in a reusable format",
            "  -s\tprint only the names of Posix `special' builtins",
            "",
            "Options controlling dynamic loading:",
            "  -f\tLoad builtin NAME from shared object FILENAME",
            "  -d\tRemove a builtin loaded with -f",
            "",
            "Without options, each NAME is enabled.",
            "",
            "On systems with dynamic loading, the shell variable BASH_LOADABLES_PATH",
            "defines a search path for the directory containing FILENAMEs that do",
            "not contain a slash. It may include \".\" to force a search of the current",
            "directory.",
            "",
            "To use the `test' found in $PATH instead of the shell builtin",
            "version, type `enable -n test'.",
            "",
            "Exit Status:",
            "Returns success unless NAME is not a shell builtin or an error occurs.",
        ],
        trailing_newline: false,
    },
    // eval.def
    HelpTopic {
        name: "eval",
        short_doc: "eval [arg ...]",
        doc: &[
            "Execute arguments as a shell command.",
            "",
            "Combine ARGs into a single string, use the result as input to the shell,",
            "and execute the resulting commands.",
            "",
            "Exit Status:",
            "Returns exit status of command or success if command is null.",
        ],
        trailing_newline: false,
    },
    // exec.def
    HelpTopic {
        name: "exec",
        short_doc: "exec [-cl] [-a name] [command [argument ...]] [redirection ...]",
        doc: &[
            "Replace the shell with the given command.",
            "",
            "Execute COMMAND, replacing this shell with the specified program.",
            "ARGUMENTS become the arguments to COMMAND.  If COMMAND is not specified,",
            "any redirections take effect in the current shell.",
            "",
            "Options:",
            "  -a name\tpass NAME as the zeroth argument to COMMAND",
            "  -c\texecute COMMAND with an empty environment",
            "  -l\tplace a dash in the zeroth argument to COMMAND",
            "",
            "If the command cannot be executed, a non-interactive shell exits, unless",
            "the shell option `execfail' is set.",
            "",
            "Exit Status:",
            "Returns success unless COMMAND is not found or a redirection error occurs.",
        ],
        trailing_newline: false,
    },
    // exit.def
    HelpTopic {
        name: "exit",
        short_doc: "exit [n]",
        doc: &[
            "Exit the shell.",
            "",
            "Exits the shell with a status of N.  If N is omitted, the exit status",
            "is that of the last command executed.",
        ],
        trailing_newline: false,
    },
    // setattr.def
    HelpTopic {
        name: "export",
        short_doc: "export [-fn] [name[=value] ...] or export -p [-f]",
        doc: &[
            "Set export attribute for shell variables.",
            "",
            "Marks each NAME for automatic export to the environment of subsequently",
            "executed commands.  If VALUE is supplied, assign VALUE before exporting.",
            "",
            "Options:",
            "  -f\trefer to shell functions",
            "  -n\tremove the export property from each NAME",
            "  -p\tdisplay a list of all exported variables or functions",
            "",
            "An argument of `--' disables further option processing.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or NAME is invalid.",
        ],
        trailing_newline: false,
    },
    // colon.def
    HelpTopic {
        name: "false",
        short_doc: "false",
        doc: &[
            "Return an unsuccessful result.",
            "",
            "Exit Status:",
            "Always fails.",
        ],
        trailing_newline: false,
    },
    // fc.def
    HelpTopic {
        name: "fc",
        short_doc: "fc [-e ename] [-lnr] [first] [last] or fc -s [pat=rep] [command]",
        doc: &[
            "Display or execute commands from the history list.",
            "",
            "fc is used to list or edit and re-execute commands from the history list.",
            "FIRST and LAST can be numbers specifying the range, or FIRST can be a",
            "string, which means the most recent command beginning with that",
            "string.",
            "",
            "Options:",
            "  -e ENAME\tselect which editor to use.  Default is FCEDIT, then EDITOR,",
            "\t\tthen vi",
            "  -l \tlist lines instead of editing",
            "  -n\tomit line numbers when listing",
            "  -r\treverse the order of the lines (newest listed first)",
            "",
            "With the `fc -s [pat=rep ...] [command]' format, COMMAND is",
            "re-executed after the substitution OLD=NEW is performed.",
            "",
            "A useful alias to use with this is r='fc -s', so that typing `r cc'",
            "runs the last command beginning with `cc' and typing `r' re-executes",
            "the last command.",
            "",
            "The history builtin also operates on the history list.",
            "",
            "Exit Status:",
            "Returns success or status of executed command; non-zero if an error occurs.",
        ],
        trailing_newline: false,
    },
    // fg_bg.def
    HelpTopic {
        name: "fg",
        short_doc: "fg [job_spec]",
        doc: &[
            "Move job to the foreground.",
            "",
            "Place the job identified by JOB_SPEC in the foreground, making it the",
            "current job.  If JOB_SPEC is not present, the shell's notion of the",
            "current job is used.",
            "",
            "Exit Status:",
            "Status of command placed in foreground, or failure if an error occurs.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "for",
        short_doc: "for NAME [in WORDS ... ] ; do COMMANDS; done",
        doc: &[
            "Execute commands for each member in a list.",
            "",
            "The `for' loop executes a sequence of commands for each member in a",
            "list of items.  If `in WORDS ...;' is not present, then `in \"$@\"' is",
            "assumed.  For each element in WORDS, NAME is set to that element, and",
            "the COMMANDS are executed.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "for ((",
        short_doc: "for (( exp1; exp2; exp3 )); do COMMANDS; done",
        doc: &[
            "Arithmetic for loop.",
            "",
            "Equivalent to",
            "\t(( EXP1 ))",
            "\twhile (( EXP2 )); do",
            "\t\tCOMMANDS",
            "\t\t(( EXP3 ))",
            "\tdone",
            "EXP1, EXP2, and EXP3 are arithmetic expressions.  If any expression is",
            "omitted, it behaves as if it evaluates to 1.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "function",
        short_doc: "function name { COMMANDS ; } or name () { COMMANDS ; }",
        doc: &[
            "Define shell function.",
            "",
            "Create a shell function named NAME.  When invoked as a simple command,",
            "NAME runs COMMANDs in the calling shell's context.  When NAME is invoked,",
            "the arguments are passed to the function as $1...$n, and the function's",
            "name is in $FUNCNAME.",
            "",
            "Exit Status:",
            "Returns success unless NAME is readonly.",
        ],
        trailing_newline: false,
    },
    // getopts.def
    HelpTopic {
        name: "getopts",
        short_doc: "getopts optstring name [arg ...]",
        doc: &[
            "Parse option arguments.",
            "",
            "Getopts is used by shell procedures to parse positional parameters",
            "as options.",
            "",
            "OPTSTRING contains the option letters to be recognized; if a letter",
            "is followed by a colon, the option is expected to have an argument,",
            "which should be separated from it by white space.",
            "",
            "Each time it is invoked, getopts will place the next option in the",
            "shell variable $name, initializing name if it does not exist, and",
            "the index of the next argument to be processed into the shell",
            "variable OPTIND.  OPTIND is initialized to 1 each time the shell or",
            "a shell script is invoked.  When an option requires an argument,",
            "getopts places that argument into the shell variable OPTARG.",
            "",
            "getopts reports errors in one of two ways.  If the first character",
            "of OPTSTRING is a colon, getopts uses silent error reporting.  In",
            "this mode, no error messages are printed.  If an invalid option is",
            "seen, getopts places the option character found into OPTARG.  If a",
            "required argument is not found, getopts places a ':' into NAME and",
            "sets OPTARG to the option character found.  If getopts is not in",
            "silent mode, and an invalid option is seen, getopts places '?' into",
            "NAME and unsets OPTARG.  If a required argument is not found, a '?'",
            "is placed in NAME, OPTARG is unset, and a diagnostic message is",
            "printed.",
            "",
            "If the shell variable OPTERR has the value 0, getopts disables the",
            "printing of error messages, even if the first character of",
            "OPTSTRING is not a colon.  OPTERR has the value 1 by default.",
            "",
            "Getopts normally parses the positional parameters, but if arguments",
            "are supplied as ARG values, they are parsed instead.",
            "",
            "Exit Status:",
            "Returns success if an option is found; fails if the end of options is",
            "encountered or an error occurs.",
        ],
        trailing_newline: false,
    },
    // hash.def
    HelpTopic {
        name: "hash",
        short_doc: "hash [-lr] [-p pathname] [-dt] [name ...]",
        doc: &[
            "Remember or display program locations.",
            "",
            "Determine and remember the full pathname of each command NAME.  If",
            "no arguments are given, information about remembered commands is displayed.",
            "",
            "Options:",
            "  -d\tforget the remembered location of each NAME",
            "  -l\tdisplay in a format that may be reused as input",
            "  -p pathname\tuse PATHNAME as the full pathname of NAME",
            "  -r\tforget all remembered locations",
            "  -t\tprint the remembered location of each NAME, preceding",
            "\t\teach location with the corresponding NAME if multiple",
            "\t\tNAMEs are given",
            "Arguments:",
            "  NAME\tEach NAME is searched for in $PATH and added to the list",
            "\t\tof remembered commands.",
            "",
            "Exit Status:",
            "Returns success unless NAME is not found or an invalid option is given.",
        ],
        trailing_newline: false,
    },
    // help.def
    HelpTopic {
        name: "help",
        short_doc: "help [-dms] [pattern ...]",
        doc: &[
            "Display information about builtin commands.",
            "",
            "Displays brief summaries of builtin commands.  If PATTERN is",
            "specified, gives detailed help on all commands matching PATTERN,",
            "otherwise the list of help topics is printed.",
            "",
            "Options:",
            "  -d\toutput short description for each topic",
            "  -m\tdisplay usage in pseudo-manpage format",
            "  -s\toutput only a short usage synopsis for each topic matching",
            "\t\tPATTERN",
            "",
            "Arguments:",
            "  PATTERN\tPattern specifying a help topic",
            "",
            "Exit Status:",
            "Returns success unless PATTERN is not found or an invalid option is given.",
        ],
        trailing_newline: false,
    },
    // history.def
    HelpTopic {
        name: "history",
        short_doc: "history [-c] [-d offset] [n] or history -anrw [filename] or history -ps arg [arg...]",
        doc: &[
            "Display or manipulate the history list.",
            "",
            "Display the history list with line numbers, prefixing each modified",
            "entry with a `*'.  An argument of N lists only the last N entries.",
            "",
            "Options:",
            "  -c\tclear the history list by deleting all of the entries",
            "  -d offset\tdelete the history entry at position OFFSET. Negative",
            "\t\toffsets count back from the end of the history list",
            "  -d start-end\tdelete the history entries beginning at position START",
            "\t\tthrough position END.",
            "",
            "  -a\tappend history lines from this session to the history file",
            "  -n\tread all history lines not already read from the history file",
            "\t\tand append them to the history list",
            "  -r\tread the history file and append the contents to the history",
            "\t\tlist",
            "  -w\twrite the current history to the history file",
            "",
            "  -p\tperform history expansion on each ARG and display the result",
            "\t\twithout storing it in the history list",
            "  -s\tappend the ARGs to the history list as a single entry",
            "",
            "If FILENAME is given, it is used as the history file.  Otherwise,",
            "if HISTFILE has a value, that is used. If FILENAME is not supplied",
            "and HISTFILE is unset or null, the -a, -n, -r, and -w options have",
            "no effect and return success.",
            "",
            "The fc builtin also operates on the history list.",
            "",
            "If the HISTTIMEFORMAT variable is set and not null, its value is used",
            "as a format string for strftime(3) to print the time stamp associated",
            "with each displayed history entry.  No time stamps are printed otherwise.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or an error occurs.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "if",
        short_doc: "if COMMANDS; then COMMANDS; [ elif COMMANDS; then COMMANDS; ]... [ else COMMANDS; ] fi",
        doc: &[
            "Execute commands based on conditional.",
            "",
            "The `if COMMANDS' list is executed.  If its exit status is zero, then the",
            "`then COMMANDS' list is executed.  Otherwise, each `elif COMMANDS' list is",
            "executed in turn, and if its exit status is zero, the corresponding",
            "`then COMMANDS' list is executed and the if command completes.  Otherwise,",
            "the `else COMMANDS' list is executed, if present.  The exit status of the",
            "entire construct is the exit status of the last command executed, or zero",
            "if no condition tested true.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // jobs.def
    HelpTopic {
        name: "jobs",
        short_doc: "jobs [-lnprs] [jobspec ...] or jobs -x command [args]",
        doc: &[
            "Display status of jobs.",
            "",
            "Lists the active jobs.  JOBSPEC restricts output to that job.",
            "Without options, the status of all active jobs is displayed.",
            "",
            "Options:",
            "  -l\tlists process IDs in addition to the normal information",
            "  -n\tlists only processes that have changed status since the last",
            "\t\tnotification",
            "  -p\tlists process IDs only",
            "  -r\trestrict output to running jobs",
            "  -s\trestrict output to stopped jobs",
            "",
            "If -x is supplied, COMMAND is run after all job specifications that",
            "appear in ARGS have been replaced with the process ID of that job's",
            "process group leader.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or an error occurs.",
            "If -x is used, returns the exit status of COMMAND.",
        ],
        trailing_newline: false,
    },
    // kill.def
    HelpTopic {
        name: "kill",
        short_doc: "kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]",
        doc: &[
            "Send a signal to a job.",
            "",
            "Send the processes identified by PID or JOBSPEC the signal named by",
            "SIGSPEC or SIGNUM.  If neither SIGSPEC nor SIGNUM is present, then",
            "SIGTERM is assumed.",
            "",
            "Options:",
            "  -s sig\tSIG is a signal name",
            "  -n sig\tSIG is a signal number",
            "  -l\tlist the signal names; if arguments follow `-l' they are",
            "\t\tassumed to be signal numbers for which names should be listed",
            "  -L\tsynonym for -l",
            "",
            "Kill is a shell builtin for two reasons: it allows job IDs to be used",
            "instead of process IDs, and allows processes to be killed if the limit",
            "on processes that you can create is reached.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or an error occurs.",
        ],
        trailing_newline: false,
    },
    // let.def
    HelpTopic {
        name: "let",
        short_doc: "let arg [arg ...]",
        doc: &[
            "Evaluate arithmetic expressions.",
            "",
            "Evaluate each ARG as an arithmetic expression.  Evaluation is done in",
            "fixed-width integers with no check for overflow, though division by 0",
            "is trapped and flagged as an error.  The following list of operators is",
            "grouped into levels of equal-precedence operators.  The levels are listed",
            "in order of decreasing precedence.",
            "",
            "\tid++, id--\tvariable post-increment, post-decrement",
            "\t++id, --id\tvariable pre-increment, pre-decrement",
            "\t-, +\t\tunary minus, plus",
            "\t!, ~\t\tlogical and bitwise negation",
            "\t**\t\texponentiation",
            "\t*, /, %\t\tmultiplication, division, remainder",
            "\t+, -\t\taddition, subtraction",
            "\t<<, >>\t\tleft and right bitwise shifts",
            "\t<=, >=, <, >\tcomparison",
            "\t==, !=\t\tequality, inequality",
            "\t&\t\tbitwise AND",
            "\t^\t\tbitwise XOR",
            "\t|\t\tbitwise OR",
            "\t&&\t\tlogical AND",
            "\t||\t\tlogical OR",
            "\texpr ? expr : expr",
            "\t\t\tconditional operator",
            "\t=, *=, /=, %=,",
            "\t+=, -=, <<=, >>=,",
            "\t&=, ^=, |=\tassignment",
            "",
            "Shell variables are allowed as operands.  The name of the variable",
            "is replaced by its value (coerced to a fixed-width integer) within",
            "an expression.  The variable need not have its integer attribute",
            "turned on to be used in an expression.",
            "",
            "Operators are evaluated in order of precedence.  Sub-expressions in",
            "parentheses are evaluated first and may override the precedence",
            "rules above.",
            "",
            "Exit Status:",
            "If the last ARG evaluates to 0, let returns 1; let returns 0 otherwise.",
        ],
        trailing_newline: false,
    },
    // declare.def
    HelpTopic {
        name: "local",
        short_doc: "local [option] name[=value] ...",
        doc: &[
            "Define local variables.",
            "",
            "Create a local variable called NAME, and give it VALUE.  OPTION can",
            "be any option accepted by `declare'.",
            "",
            "If any NAME is \"-\", local saves the set of shell options and restores",
            "them when the function returns.",
            "",
            "Local variables can only be used within a function; they are visible",
            "only to the function where they are defined and its children.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied, a variable",
            "assignment error occurs, or the shell is not executing a function.",
        ],
        trailing_newline: false,
    },
    // exit.def
    HelpTopic {
        name: "logout",
        short_doc: "logout [n]",
        doc: &[
            "Exit a login shell.",
            "",
            "Exits a login shell with exit status N.  Returns an error if not executed",
            "in a login shell.",
        ],
        trailing_newline: false,
    },
    // mapfile.def
    HelpTopic {
        name: "mapfile",
        short_doc: "mapfile [-d delim] [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]",
        doc: &[
            "Read lines from the standard input into an indexed array variable.",
            "",
            "Read lines from the standard input into the indexed array variable ARRAY, or",
            "from file descriptor FD if the -u option is supplied.  The variable MAPFILE",
            "is the default ARRAY.",
            "",
            "Options:",
            "  -d delim\tUse DELIM to terminate lines, instead of newline",
            "  -n count\tCopy at most COUNT lines.  If COUNT is 0, all lines are copied",
            "  -O origin\tBegin assigning to ARRAY at index ORIGIN.  The default index is 0",
            "  -s count\tDiscard the first COUNT lines read",
            "  -t\tRemove a trailing DELIM from each line read (default newline)",
            "  -u fd\tRead lines from file descriptor FD instead of the standard input",
            "  -C callback\tEvaluate CALLBACK each time QUANTUM lines are read",
            "  -c quantum\tSpecify the number of lines read between each call to",
            "\t\t\tCALLBACK",
            "",
            "Arguments:",
            "  ARRAY\tArray variable name to use for file data",
            "",
            "If -C is supplied without -c, the default quantum is 5000.  When",
            "CALLBACK is evaluated, it is supplied the index of the next array",
            "element to be assigned and the line to be assigned to that element",
            "as additional arguments.",
            "",
            "If not supplied with an explicit origin, mapfile will clear ARRAY before",
            "assigning to it.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or ARRAY is readonly or",
            "not an indexed array.",
        ],
        trailing_newline: false,
    },
    // pushd.def
    HelpTopic {
        name: "popd",
        short_doc: "popd [-n] [+N | -N]",
        doc: &[
            "Remove directories from stack.",
            "",
            "Removes entries from the directory stack.  With no arguments, removes",
            "the top directory from the stack, and changes to the new top directory.",
            "",
            "Options:",
            "  -n\tSuppresses the normal change of directory when removing",
            "\t\tdirectories from the stack, so only the stack is manipulated.",
            "",
            "Arguments:",
            "  +N\tRemoves the Nth entry counting from the left of the list",
            "\t\tshown by `dirs', starting with zero.  For example: `popd +0'",
            "\t\tremoves the first directory, `popd +1' the second.",
            "",
            "  -N\tRemoves the Nth entry counting from the right of the list",
            "\t\tshown by `dirs', starting with zero.  For example: `popd -0'",
            "\t\tremoves the last directory, `popd -1' the next to last.",
            "",
            "The `dirs' builtin displays the directory stack.",
            "",
            "Exit Status:",
            "Returns success unless an invalid argument is supplied or the directory",
            "change fails.",
        ],
        trailing_newline: false,
    },
    // printf.def
    HelpTopic {
        name: "printf",
        short_doc: "printf [-v var] format [arguments]",
        doc: &[
            "Formats and prints ARGUMENTS under control of the FORMAT.",
            "",
            "Options:",
            "  -v var\tassign the output to shell variable VAR rather than",
            "\t\tdisplay it on the standard output",
            "",
            "FORMAT is a character string which contains three types of objects: plain",
            "characters, which are simply copied to standard output; character escape",
            "sequences, which are converted and copied to the standard output; and",
            "format specifications, each of which causes printing of the next successive",
            "argument.",
            "",
            "In addition to the standard format characters csndiouxXeEfFgGaA described",
            "in printf(3), printf interprets:",
            "",
            "  %b\texpand backslash escape sequences in the corresponding argument",
            "  %q\tquote the argument in a way that can be reused as shell input",
            "  %Q\tlike %q, but apply any precision to the unquoted argument before",
            "\t\tquoting",
            "  %(fmt)T\toutput the date-time string resulting from using FMT as a format",
            "\t        string for strftime(3)",
            "",
            "The format is re-used as necessary to consume all of the arguments.  If",
            "there are fewer arguments than the format requires,  extra format",
            "specifications behave as if a zero value or null string, as appropriate,",
            "had been supplied.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or a write or assignment",
            "error occurs.",
        ],
        trailing_newline: false,
    },
    // pushd.def
    HelpTopic {
        name: "pushd",
        short_doc: "pushd [-n] [+N | -N | dir]",
        doc: &[
            "Add directories to stack.",
            "",
            "Adds a directory to the top of the directory stack, or rotates",
            "the stack, making the new top of the stack the current working",
            "directory.  With no arguments, exchanges the top two directories.",
            "",
            "Options:",
            "  -n\tSuppresses the normal change of directory when adding",
            "\t\tdirectories to the stack, so only the stack is manipulated.",
            "",
            "Arguments:",
            "  +N\tRotates the stack so that the Nth directory (counting",
            "\t\tfrom the left of the list shown by `dirs', starting with",
            "\t\tzero) is at the top.",
            "",
            "  -N\tRotates the stack so that the Nth directory (counting",
            "\t\tfrom the right of the list shown by `dirs', starting with",
            "\t\tzero) is at the top.",
            "",
            "  dir\tAdds DIR to the directory stack at the top, making it the",
            "\t\tnew current working directory.",
            "",
            "The `dirs' builtin displays the directory stack.",
            "",
            "Exit Status:",
            "Returns success unless an invalid argument is supplied or the directory",
            "change fails.",
        ],
        trailing_newline: false,
    },
    // cd.def
    HelpTopic {
        name: "pwd",
        short_doc: "pwd [-LP]",
        doc: &[
            "Print the name of the current working directory.",
            "",
            "Options:",
            "  -L\tprint the value of $PWD if it names the current working",
            "\t\tdirectory",
            "  -P\tprint the physical directory, without any symbolic links",
            "",
            "By default, `pwd' behaves as if `-L' were specified.",
            "",
            "Exit Status:",
            "Returns 0 unless an invalid option is given or the current directory",
            "cannot be read.",
        ],
        trailing_newline: false,
    },
    // read.def
    HelpTopic {
        name: "read",
        short_doc: "read [-Eers] [-a array] [-d delim] [-i text] [-n nchars] [-N nchars] [-p prompt] [-t timeout] [-u fd] [name ...]",
        doc: &[
            "Read a line from the standard input and split it into fields.",
            "",
            "Reads a single line from the standard input, or from file descriptor FD",
            "if the -u option is supplied.  The line is split into fields as with word",
            "splitting, and the first word is assigned to the first NAME, the second",
            "word to the second NAME, and so on, with any leftover words assigned to",
            "the last NAME.  Only the characters found in $IFS are recognized as word",
            "delimiters. By default, the backslash character escapes delimiter characters",
            "and newline.",
            "",
            "If no NAMEs are supplied, the line read is stored in the REPLY variable.",
            "",
            "Options:",
            "  -a array\tassign the words read to sequential indices of the array",
            "\t\tvariable ARRAY, starting at zero",
            "  -d delim\tcontinue until the first character of DELIM is read, rather",
            "\t\tthan newline",
            "  -e\tuse Readline to obtain the line",
            "  -E\tuse Readline to obtain the line and use the bash default",
            "\t\tcompletion instead of Readline's default completion",
            "  -i text\tuse TEXT as the initial text for Readline",
            "  -n nchars\treturn after reading NCHARS characters rather than waiting",
            "\t\tfor a newline, but honor a delimiter if fewer than",
            "\t\tNCHARS characters are read before the delimiter",
            "  -N nchars\treturn only after reading exactly NCHARS characters, unless",
            "\t\tEOF is encountered or read times out, ignoring any",
            "\t\tdelimiter",
            "  -p prompt\toutput the string PROMPT without a trailing newline before",
            "\t\tattempting to read",
            "  -r\tdo not allow backslashes to escape any characters",
            "  -s\tdo not echo input coming from a terminal",
            "  -t timeout\ttime out and return failure if a complete line of",
            "\t\tinput is not read within TIMEOUT seconds.  The value of the",
            "\t\tTMOUT variable is the default timeout.  TIMEOUT may be a",
            "\t\tfractional number.  If TIMEOUT is 0, read returns",
            "\t\timmediately, without trying to read any data, returning",
            "\t\tsuccess only if input is available on the specified",
            "\t\tfile descriptor.  The exit status is greater than 128",
            "\t\tif the timeout is exceeded",
            "  -u fd\tread from file descriptor FD instead of the standard input",
            "",
            "Exit Status:",
            "The return code is zero, unless end-of-file is encountered, read times out",
            "(in which case it's greater than 128), a variable assignment error occurs,",
            "or an invalid file descriptor is supplied as the argument to -u.",
        ],
        trailing_newline: false,
    },
    // mapfile.def
    HelpTopic {
        name: "readarray",
        short_doc: "readarray [-d delim] [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]",
        doc: &[
            "Read lines from a file into an array variable.",
            "",
            "A synonym for `mapfile'.",
        ],
        trailing_newline: false,
    },
    // setattr.def
    HelpTopic {
        name: "readonly",
        short_doc: "readonly [-aAf] [name[=value] ...] or readonly -p",
        doc: &[
            "Mark shell variables as unchangeable.",
            "",
            "Mark each NAME as read-only; the values of these NAMEs may not be",
            "changed by subsequent assignment.  If VALUE is supplied, assign VALUE",
            "before marking as read-only.",
            "",
            "Options:",
            "  -a\trefer to indexed array variables",
            "  -A\trefer to associative array variables",
            "  -f\trefer to shell functions",
            "  -p\tdisplay a list of all readonly variables or functions,",
            "\t\tdepending on whether or not the -f option is given",
            "",
            "An argument of `--' disables further option processing.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or NAME is invalid.",
        ],
        trailing_newline: false,
    },
    // return.def
    HelpTopic {
        name: "return",
        short_doc: "return [n]",
        doc: &[
            "Return from a shell function.",
            "",
            "Causes a function or sourced script to exit with the return value",
            "specified by N.  If N is omitted, the return status is that of the",
            "last command executed within the function or script.",
            "",
            "Exit Status:",
            "Returns N, or failure if the shell is not executing a function or script.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "select",
        short_doc: "select NAME [in WORDS ... ;] do COMMANDS; done",
        doc: &[
            "Select words from a list and execute commands.",
            "",
            "The WORDS are expanded, generating a list of words.  The",
            "set of expanded words is printed on the standard error, each",
            "preceded by a number.  If `in WORDS' is not present, `in \"$@\"'",
            "is assumed.  The PS3 prompt is then displayed and a line read",
            "from the standard input.  If the line consists of the number",
            "corresponding to one of the displayed words, then NAME is set",
            "to that word.  If the line is empty, WORDS and the prompt are",
            "redisplayed.  If EOF is read, the command completes.  Any other",
            "value read causes NAME to be set to null.  The line read is saved",
            "in the variable REPLY.  COMMANDS are executed after each selection",
            "until a break command is executed.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // set.def
    HelpTopic {
        name: "set",
        short_doc: "set [-abefhkmnptuvxBCEHPT] [-o option-name] [--] [-] [arg ...]",
        doc: &[
            "Set or unset values of shell options and positional parameters.",
            "",
            "Change the value of shell attributes and positional parameters, or",
            "display the names and values of shell variables.",
            "",
            "Options:",
            "  -a  Mark variables which are modified or created for export.",
            "  -b  Notify of job termination immediately.",
            "  -e  Exit immediately if a command exits with a non-zero status.",
            "  -f  Disable file name generation (globbing).",
            "  -h  Remember the location of commands as they are looked up.",
            "  -k  All assignment arguments are placed in the environment for a",
            "      command, not just those that precede the command name.",
            "  -m  Job control is enabled.",
            "  -n  Read commands but do not execute them.",
            "  -o option-name",
            "      Set the variable corresponding to option-name:",
            "          allexport    same as -a",
            "          braceexpand  same as -B",
            "          emacs        use an emacs-style line editing interface",
            "          errexit      same as -e",
            "          errtrace     same as -E",
            "          functrace    same as -T",
            "          hashall      same as -h",
            "          histexpand   same as -H",
            "          history      enable command history",
            "          ignoreeof    the shell will not exit upon reading EOF",
            "          interactive-comments",
            "                       allow comments to appear in interactive commands",
            "          keyword      same as -k",
            "          monitor      same as -m",
            "          noclobber    same as -C",
            "          noexec       same as -n",
            "          noglob       same as -f",
            "          nolog        currently accepted but ignored",
            "          notify       same as -b",
            "          nounset      same as -u",
            "          onecmd       same as -t",
            "          physical     same as -P",
            "          pipefail     the return value of a pipeline is the status of",
            "                       the last command to exit with a non-zero status,",
            "                       or zero if no command exited with a non-zero status",
            "          posix        change the behavior of bash where the default",
            "                       operation differs from the Posix standard to",
            "                       match the standard",
            "          privileged   same as -p",
            "          verbose      same as -v",
            "          vi           use a vi-style line editing interface",
            "          xtrace       same as -x",
            "  -p  Turned on whenever the real and effective user ids do not match.",
            "      Disables processing of the $ENV file and importing of shell",
            "      functions.  Turning this option off causes the effective uid and",
            "      gid to be set to the real uid and gid.",
            "  -t  Exit after reading and executing one command.",
            "  -u  Treat unset variables as an error when substituting.",
            "  -v  Print shell input lines as they are read.",
            "  -x  Print commands and their arguments as they are executed.",
            "  -B  the shell will perform brace expansion",
            "  -C  If set, disallow existing regular files to be overwritten",
            "      by redirection of output.",
            "  -E  If set, the ERR trap is inherited by shell functions.",
            "  -H  Enable ! style history substitution.  This flag is on",
            "      by default when the shell is interactive.",
            "  -P  If set, do not resolve symbolic links when executing commands",
            "      such as cd which change the current directory.",
            "  -T  If set, the DEBUG and RETURN traps are inherited by shell functions.",
            "  --  Assign any remaining arguments to the positional parameters.",
            "      If there are no remaining arguments, the positional parameters",
            "      are unset.",
            "  -   Assign any remaining arguments to the positional parameters.",
            "      The -x and -v options are turned off.",
            "",
            "If -o is supplied with no option-name, set prints the current shell",
            "option settings. If +o is supplied with no option-name, set prints a",
            "series of set commands to recreate the current option settings.",
            "",
            "Using + rather than - causes these flags to be turned off.  The",
            "flags can also be used upon invocation of the shell.  The current",
            "set of flags may be found in $-.  The remaining n ARGs are positional",
            "parameters and are assigned, in order, to $1, $2, .. $n.  If no",
            "ARGs are given, all shell variables are printed.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given.",
        ],
        trailing_newline: false,
    },
    // shift.def
    HelpTopic {
        name: "shift",
        short_doc: "shift [n]",
        doc: &[
            "Shift positional parameters.",
            "",
            "Rename the positional parameters $N+1,$N+2 ... to $1,$2 ...  If N is",
            "not given, it is assumed to be 1.",
            "",
            "Exit Status:",
            "Returns success unless N is negative or greater than $#.",
        ],
        trailing_newline: false,
    },
    // shopt.def
    HelpTopic {
        name: "shopt",
        short_doc: "shopt [-pqsu] [-o] [optname ...]",
        doc: &[
            "Set and unset shell options.",
            "",
            "Change the setting of each shell option OPTNAME.  Without any option",
            "arguments, list each supplied OPTNAME, or all shell options if no",
            "OPTNAMEs are given, with an indication of whether or not each is set.",
            "",
            "Options:",
            "  -o\trestrict OPTNAMEs to those defined for use with `set -o'",
            "  -p\tprint each shell option with an indication of its status",
            "  -q\tsuppress output",
            "  -s\tenable (set) each OPTNAME",
            "  -u\tdisable (unset) each OPTNAME",
            "",
            "Exit Status:",
            "Returns success if OPTNAME is enabled; fails if an invalid option is",
            "given or OPTNAME is disabled.",
        ],
        trailing_newline: false,
    },
    // source.def
    HelpTopic {
        name: "source",
        short_doc: "source [-p path] filename [arguments]",
        doc: &[
            "Execute commands from a file in the current shell.",
            "",
            "Read and execute commands from FILENAME in the current shell. If the",
            "-p option is supplied, the PATH argument is treated as a colon-",
            "separated list of directories to search for FILENAME. If -p is not",
            "supplied, $PATH is searched to find FILENAME. If any ARGUMENTS are",
            "supplied, they become the positional parameters when FILENAME is executed.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed in FILENAME; fails if",
            "FILENAME cannot be read.",
        ],
        trailing_newline: false,
    },
    // suspend.def
    HelpTopic {
        name: "suspend",
        short_doc: "suspend [-f]",
        doc: &[
            "Suspend shell execution.",
            "",
            "Suspend the execution of this shell until it receives a SIGCONT signal.",
            "Unless forced, login shells and shells without job control cannot be",
            "suspended.",
            "",
            "Options:",
            "  -f\tforce the suspend, even if the shell is a login shell or job",
            "\t\tcontrol is not enabled.",
            "",
            "Exit Status:",
            "Returns success unless job control is not enabled or an error occurs.",
        ],
        trailing_newline: false,
    },
    // test.def
    HelpTopic {
        name: "test",
        short_doc: "test [expr]",
        doc: &[
            "Evaluate conditional expression.",
            "",
            "Exits with a status of 0 (true) or 1 (false) depending on",
            "the evaluation of EXPR.  Expressions may be unary or binary.  Unary",
            "expressions are often used to examine the status of a file.  There",
            "are string operators and numeric comparison operators as well.",
            "",
            "The behavior of test depends on the number of arguments.  Read the",
            "bash manual page for the complete specification.",
            "",
            "File operators:",
            "",
            "  -a FILE        True if file exists.",
            "  -b FILE        True if file is block special.",
            "  -c FILE        True if file is character special.",
            "  -d FILE        True if file is a directory.",
            "  -e FILE        True if file exists.",
            "  -f FILE        True if file exists and is a regular file.",
            "  -g FILE        True if file is set-group-id.",
            "  -h FILE        True if file is a symbolic link.",
            "  -L FILE        True if file is a symbolic link.",
            "  -k FILE        True if file has its `sticky' bit set.",
            "  -p FILE        True if file is a named pipe.",
            "  -r FILE        True if file is readable by you.",
            "  -s FILE        True if file exists and is not empty.",
            "  -S FILE        True if file is a socket.",
            "  -t FD          True if FD is opened on a terminal.",
            "  -u FILE        True if the file is set-user-id.",
            "  -w FILE        True if the file is writable by you.",
            "  -x FILE        True if the file is executable by you.",
            "  -O FILE        True if the file is effectively owned by you.",
            "  -G FILE        True if the file is effectively owned by your group.",
            "  -N FILE        True if the file has been modified since it was last read.",
            "",
            "  FILE1 -nt FILE2  True if file1 is newer than file2 (according to",
            "                   modification date).",
            "",
            "  FILE1 -ot FILE2  True if file1 is older than file2.",
            "",
            "  FILE1 -ef FILE2  True if file1 is a hard link to file2.",
            "",
            "String operators:",
            "",
            "  -z STRING      True if string is empty.",
            "",
            "  -n STRING",
            "     STRING      True if string is not empty.",
            "",
            "  STRING1 = STRING2",
            "                 True if the strings are equal.",
            "  STRING1 != STRING2",
            "                 True if the strings are not equal.",
            "  STRING1 < STRING2",
            "                 True if STRING1 sorts before STRING2 lexicographically.",
            "  STRING1 > STRING2",
            "                 True if STRING1 sorts after STRING2 lexicographically.",
            "",
            "Other operators:",
            "",
            "  -o OPTION      True if the shell option OPTION is enabled.",
            "  -v VAR         True if the shell variable VAR is set.",
            "  -R VAR         True if the shell variable VAR is set and is a name",
            "                 reference.",
            "  ! EXPR         True if expr is false.",
            "  EXPR1 -a EXPR2 True if both expr1 AND expr2 are true.",
            "  EXPR1 -o EXPR2 True if either expr1 OR expr2 is true.",
            "",
            "  arg1 OP arg2   Arithmetic tests.  OP is one of -eq, -ne,",
            "                 -lt, -le, -gt, or -ge.",
            "",
            "Arithmetic binary operators return true if ARG1 is equal, not-equal,",
            "less-than, less-than-or-equal, greater-than, or greater-than-or-equal",
            "than ARG2.",
            "",
            "Exit Status:",
            "Returns success if EXPR evaluates to true; fails if EXPR evaluates to",
            "false or an invalid argument is given.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "time",
        short_doc: "time [-p] pipeline",
        doc: &[
            "Report time consumed by pipeline's execution.",
            "",
            "Execute PIPELINE and print a summary of the real time, user CPU time,",
            "and system CPU time spent executing PIPELINE when it terminates.",
            "",
            "Options:",
            "  -p\tprint the timing summary in the portable Posix format",
            "",
            "The value of the TIMEFORMAT variable is used as the output format.",
            "",
            "Exit Status:",
            "The return status is the return status of PIPELINE.",
        ],
        trailing_newline: false,
    },
    // times.def
    HelpTopic {
        name: "times",
        short_doc: "times",
        doc: &[
            "Display process times.",
            "",
            "Prints the accumulated user and system times for the shell and all of its",
            "child processes.",
            "",
            "Exit Status:",
            "Always succeeds.",
        ],
        trailing_newline: false,
    },
    // trap.def
    HelpTopic {
        name: "trap",
        short_doc: "trap [-Plp] [[action] signal_spec ...]",
        doc: &[
            "Trap signals and other events.",
            "",
            "Defines and activates handlers to be run when the shell receives signals",
            "or other conditions.",
            "",
            "ACTION is a command to be read and executed when the shell receives the",
            "signal(s) SIGNAL_SPEC.  If ACTION is absent (and a single SIGNAL_SPEC",
            "is supplied) or `-', each specified signal is reset to its original",
            "value.  If ACTION is the null string each SIGNAL_SPEC is ignored by the",
            "shell and by the commands it invokes.",
            "",
            "If a SIGNAL_SPEC is EXIT (0) ACTION is executed on exit from the shell.",
            "If a SIGNAL_SPEC is DEBUG, ACTION is executed before every simple command",
            "and selected other commands. If a SIGNAL_SPEC is RETURN, ACTION is",
            "executed each time a shell function or a script run by the . or source",
            "builtins finishes executing.  A SIGNAL_SPEC of ERR means to execute ACTION",
            "each time a command's failure would cause the shell to exit when the -e",
            "option is enabled.",
            "",
            "If no arguments are supplied, trap prints the list of commands associated",
            "with each trapped signal in a form that may be reused as shell input to",
            "restore the same signal dispositions.",
            "",
            "Options:",
            "  -l\tprint a list of signal names and their corresponding numbers",
            "  -p\tdisplay the trap commands associated with each SIGNAL_SPEC in a",
            "\t\tform that may be reused as shell input; or for all trapped",
            "\t\tsignals if no arguments are supplied",
            "  -P\tdisplay the trap commands associated with each SIGNAL_SPEC. At least",
            "\t\tone SIGNAL_SPEC must be supplied. -P and -p cannot be used",
            "\t\ttogether.",
            "",
            "Each SIGNAL_SPEC is either a signal name in <signal.h> or a signal number.",
            "Signal names are case insensitive and the SIG prefix is optional.  A",
            "signal may be sent to the shell with \"kill -signal $$\".",
            "",
            "Exit Status:",
            "Returns success unless a SIGSPEC is invalid or an invalid option is given.",
        ],
        trailing_newline: false,
    },
    // colon.def
    HelpTopic {
        name: "true",
        short_doc: "true",
        doc: &[
            "Return a successful result.",
            "",
            "Exit Status:",
            "Always succeeds.",
        ],
        trailing_newline: false,
    },
    // type.def
    HelpTopic {
        name: "type",
        short_doc: "type [-afptP] name [name ...]",
        doc: &[
            "Display information about command type.",
            "",
            "For each NAME, indicate how it would be interpreted if used as a",
            "command name.",
            "",
            "Options:",
            "  -a\tdisplay all locations containing an executable named NAME;",
            "\t\tincludes aliases, builtins, and functions, if and only if",
            "\t\tthe `-p' option is not also used",
            "  -f\tsuppress shell function lookup",
            "  -P\tforce a PATH search for each NAME, even if it is an alias,",
            "\t\tbuiltin, or function, and returns the name of the disk file",
            "\t\tthat would be executed",
            "  -p\treturns either the name of the disk file that would be executed,",
            "\t\tor nothing if `type -t NAME' would not return `file'",
            "  -t\toutput a single word which is one of `alias', `keyword',",
            "\t\t`function', `builtin', `file' or `', if NAME is an alias,",
            "\t\tshell reserved word, shell function, shell builtin, disk file,",
            "\t\tor not found, respectively",
            "",
            "Arguments:",
            "  NAME\tCommand name to be interpreted.",
            "",
            "Exit Status:",
            "Returns success if all of the NAMEs are found; fails if any are not found.",
        ],
        trailing_newline: false,
    },
    // declare.def
    HelpTopic {
        name: "typeset",
        short_doc: "typeset [-aAfFgiIlnrtux] name[=value] ... or typeset -p [-aAfFilnrtux] [name ...]",
        doc: &[
            "Set variable values and attributes.",
            "",
            "A synonym for `declare'.  See `help declare'.",
        ],
        trailing_newline: false,
    },
    // ulimit.def
    HelpTopic {
        name: "ulimit",
        short_doc: "ulimit [-SHabcdefiklmnpqrstuvxPRT] [limit]",
        doc: &[
            "Modify shell resource limits.",
            "",
            "Provides control over the resources available to the shell and processes",
            "it creates, on systems that allow such control.",
            "",
            "Options:",
            "  -S\tuse the `soft' resource limit",
            "  -H\tuse the `hard' resource limit",
            "  -a\tall current limits are reported",
            "  -b\tthe socket buffer size",
            "  -c\tthe maximum size of core files created",
            "  -d\tthe maximum size of a process's data segment",
            "  -e\tthe maximum scheduling priority (`nice')",
            "  -f\tthe maximum size of files written by the shell and its children",
            "  -i\tthe maximum number of pending signals",
            "  -k\tthe maximum number of kqueues allocated for this process",
            "  -l\tthe maximum size a process may lock into memory",
            "  -m\tthe maximum resident set size",
            "  -n\tthe maximum number of open file descriptors",
            "  -p\tthe pipe buffer size",
            "  -q\tthe maximum number of bytes in POSIX message queues",
            "  -r\tthe maximum real-time scheduling priority",
            "  -s\tthe maximum stack size",
            "  -t\tthe maximum amount of cpu time in seconds",
            "  -u\tthe maximum number of user processes",
            "  -v\tthe size of virtual memory",
            "  -x\tthe maximum number of file locks",
            "  -P\tthe maximum number of pseudoterminals",
            "  -R\tthe maximum time a real-time process can run before blocking",
            "  -T\tthe maximum number of threads",
            "",
            "Not all options are available on all platforms.",
            "",
            "If LIMIT is given, it is the new value of the specified resource; the",
            "special LIMIT values `soft', `hard', and `unlimited' stand for the",
            "current soft limit, the current hard limit, and no limit, respectively.",
            "Otherwise, the current value of the specified resource is printed.  If",
            "no option is given, then -f is assumed.",
            "",
            "Values are in 1024-byte increments, except for -t, which is in seconds;",
            "-p, which is in increments of 512 bytes; -R, which is in microseconds;",
            "-b, which is in bytes; and -e, -i, -k, -n, -q, -r, -u, -x, and -P,",
            "which accept unscaled values.",
            "",
            "When in posix mode, values supplied with -c and -f are in 512-byte",
            "increments.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is supplied or an error occurs.",
        ],
        trailing_newline: false,
    },
    // umask.def
    HelpTopic {
        name: "umask",
        short_doc: "umask [-p] [-S] [mode]",
        doc: &[
            "Display or set file mode mask.",
            "",
            "Sets the user file-creation mask to MODE.  If MODE is omitted, prints",
            "the current value of the mask.",
            "",
            "If MODE begins with a digit, it is interpreted as an octal number;",
            "otherwise it is a symbolic mode string like that accepted by chmod(1).",
            "",
            "Options:",
            "  -p\tif MODE is omitted, output in a form that may be reused as input",
            "  -S\tmakes the output symbolic; otherwise an octal number is output",
            "",
            "Exit Status:",
            "Returns success unless MODE is invalid or an invalid option is given.",
        ],
        trailing_newline: false,
    },
    // alias.def
    HelpTopic {
        name: "unalias",
        short_doc: "unalias [-a] name [name ...]",
        doc: &[
            "Remove each NAME from the list of defined aliases.",
            "",
            "Options:",
            "  -a\tremove all alias definitions",
            "",
            "Return success unless a NAME is not an existing alias.",
        ],
        trailing_newline: false,
    },
    // set.def
    HelpTopic {
        name: "unset",
        short_doc: "unset [-f] [-v] [-n] [name ...]",
        doc: &[
            "Unset values and attributes of shell variables and functions.",
            "",
            "For each NAME, remove the corresponding variable or function.",
            "",
            "Options:",
            "  -f\ttreat each NAME as a shell function",
            "  -v\ttreat each NAME as a shell variable",
            "  -n\ttreat each NAME as a name reference and unset the variable itself",
            "\t\trather than the variable it references",
            "",
            "Without options, unset first tries to unset a variable, and if that fails,",
            "tries to unset a function.",
            "",
            "Some variables cannot be unset; also see `readonly'.",
            "",
            "Exit Status:",
            "Returns success unless an invalid option is given or a NAME is read-only.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "until",
        short_doc: "until COMMANDS; do COMMANDS-2; done",
        doc: &[
            "Execute commands as long as a test does not succeed.",
            "",
            "Expand and execute COMMANDS-2 as long as the final command in COMMANDS has",
            "an exit status which is not zero.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "variables",
        short_doc: "variables - Names and meanings of some shell variables",
        doc: &[
            "Common shell variable names and usage.",
            "",
            "BASH_VERSION\tVersion information for this Bash.",
            "CDPATH\tA colon-separated list of directories to search",
            "\t\tfor directories given as arguments to `cd'.",
            "GLOBIGNORE\tA colon-separated list of patterns describing filenames to",
            "\t\tbe ignored by pathname expansion.",
            "HISTFILE\tThe name of the file where your command history is stored.",
            "HISTFILESIZE\tThe maximum number of lines this file can contain.",
            "HISTSIZE\tThe maximum number of history lines that a running",
            "\t\tshell can access.",
            "HOME\tThe complete pathname to your login directory.",
            "HOSTNAME\tThe name of the current host.",
            "HOSTTYPE\tThe type of CPU this version of Bash is running under.",
            "IGNOREEOF\tControls the action of the shell on receipt of an EOF",
            "\t\tcharacter as the sole input.  If set, then the value",
            "\t\tof it is the number of EOF characters that can be seen",
            "\t\tin a row on an empty line before the shell will exit",
            "\t\t(default 10).  When unset, EOF signifies the end of input.",
            "MACHTYPE\tA string describing the current system Bash is running on.",
            "MAILCHECK\tHow often, in seconds, Bash checks for new mail.",
            "MAILPATH\tA colon-separated list of filenames which Bash checks",
            "\t\tfor new mail.",
            "OSTYPE\tThe version of Unix this version of Bash is running on.",
            "PATH\tA colon-separated list of directories to search when",
            "\t\tlooking for commands.",
            "PROMPT_COMMAND\tA command to be executed before the printing of each",
            "\t\tprimary prompt.",
            "PS1\t\tThe primary prompt string.",
            "PS2\t\tThe secondary prompt string.",
            "PWD\t\tThe full pathname of the current directory.",
            "SHELLOPTS\tA colon-separated list of enabled shell options.",
            "TERM\tThe name of the current terminal type.",
            "TIMEFORMAT\tThe output format for timing statistics displayed by the",
            "\t\t`time' reserved word.",
            "auto_resume\tNon-null means a command word appearing on a line by",
            "\t\titself is first looked for in the list of currently",
            "\t\tstopped jobs.  If found there, that job is foregrounded.",
            "\t\tA value of `exact' means that the command word must",
            "\t\texactly match a command in the list of stopped jobs.  A",
            "\t\tvalue of `substring' means that the command word must",
            "\t\tmatch a substring of the job.  Any other value means that",
            "\t\tthe command must be a prefix of a stopped job.",
            "histchars\tCharacters controlling history expansion and quick",
            "\t\tsubstitution.  The first character is the history",
            "\t\tsubstitution character, usually `!'.  The second is",
            "\t\tthe `quick substitution' character, usually `^'.  The",
            "\t\tthird is the `history comment' character, usually `#'.",
            "HISTIGNORE\tA colon-separated list of patterns used to decide which",
            "\t\tcommands should be saved on the history list.",
        ],
        trailing_newline: true,
    },
    // wait.def
    HelpTopic {
        name: "wait",
        short_doc: "wait [-fn] [-p var] [id ...]",
        doc: &[
            "Wait for job completion and return exit status.",
            "",
            "Waits for each process identified by an ID, which may be a process ID or a",
            "job specification, and reports its termination status.  If ID is not",
            "given, waits for all currently active child processes, and the return",
            "status is zero.  If ID is a job specification, waits for all processes",
            "in that job's pipeline.",
            "",
            "If the -n option is supplied, waits for a single job from the list of IDs,",
            "or, if no IDs are supplied, for the next job to complete and returns its",
            "exit status.",
            "",
            "If the -p option is supplied, the process or job identifier of the job",
            "for which the exit status is returned is assigned to the variable VAR",
            "named by the option argument. The variable will be unset initially, before",
            "any assignment. This is useful only when the -n option is supplied.",
            "",
            "If the -f option is supplied, and job control is enabled, waits for the",
            "specified ID to terminate, instead of waiting for it to change status.",
            "",
            "Exit Status:",
            "Returns the status of the last ID; fails if ID is invalid or an invalid",
            "option is given, or if -n is supplied and the shell has no unwaited-for",
            "children.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "while",
        short_doc: "while COMMANDS; do COMMANDS-2; done",
        doc: &[
            "Execute commands as long as a test succeeds.",
            "",
            "Expand and execute COMMANDS-2 as long as the final command in COMMANDS has",
            "an exit status of zero.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
    // reserved.def
    HelpTopic {
        name: "{ ... }",
        short_doc: "{ COMMANDS ; }",
        doc: &[
            "Group commands as a unit.",
            "",
            "Run a set of commands in a group.  This is one way to redirect an",
            "entire set of commands.",
            "",
            "Exit Status:",
            "Returns the status of the last command executed.",
        ],
        trailing_newline: false,
    },
];
